name: ci-contract-upgrade-example

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: rustfmt, clippy
    # Needed for gcc install
    - run: sudo apt update && sudo apt install -y build-essential
    - run: rustup component add rustfmt --toolchain nightly-2021-05-11-x86_64-unknown-linux-gnu
    - run: make prepare
    - run: make check-lint
    - run: make test